#!/usr/bin/env python3

import psutil

# import jc
# use `upower --monitor-detail` and parse on every update using jc
# use sockets to send any changes in information

battery = psutil.sensors_battery()
print(int(battery.percent))